trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/Data Analysis'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/Data Analysis'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/piwebapi_samples/Data Analysis'
  - name: CredFile
    value: test_config.json
  - name: CredFileLibrary
    value: product-readiness.piwebapi_data_analysis.json
  - name: covStream
    value: PIWebAPIPython
  - name: bdProject
    value: PIWebAPI_Python

jobs:
  - job: BuildUploadUtility
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: 
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '**/PIUploadUtility.sln'
          feedsToUse: 'select'
      - task: VSBuild@1
        inputs:
          solution: '**\PIUploadUtility.sln'
          configuration: Debug
      - task: CopyFiles@2
        displayName: Copy Build Output Files
        inputs:
          sourceFolder: "$(Build.SourcesDirectory)"
          targetFolder: "$(Build.BinariesDirectory)"
          contents: "**/bin/Debug/*"
          overWrite: true
          flattenFolders: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.BinariesDirectory)'
          ArtifactName: 'PIUploadUtility'
          publishLocation: 'Container'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: '&"$(Build.BinariesDirectory)"/PIUploadUtility.exe'

  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: |
          echo Install pip
          call python -m pip install --upgrade pip
          echo Install tools
          call pip install requests
          call pip install requests_kerberos
          call pip install unittest
          call pip install unittest-xml-reporting
          echo Install requirements
          call pip install -r requirements.txt
          echo Run tests
          call jupyter nbconvert --to notebook --inplace --ExecuteProcessor.timeout=6000 --execute Sandbox.ipynb
          echo Complete
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Run tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**\output.xml'
          searchFolder: $(Build.SourcesDirectory)$(projPath)
          testRunTitle: 'Publish test results'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: python
